from pyswip import Prolog

prolog = Prolog()
# prolog.assertz('index("disease", "symptom")')
prolog.assertz('index("acne","bultos dolorosos, llenos de pus que estan debajo de la superficie de la piel")')
prolog.assertz('index("acne","bultos grandes, solidos y dolorosos que estan debajo de la superficie de la piel")')
prolog.assertz('index("acne","comedones abiertos (poros abiertos)")')
prolog.assertz('index("acne","comedones cerrados (poros tapados)")')
prolog.assertz('index("acne","granos que son papulas con pus en la punta")')
prolog.assertz('index("acne","indigestion")')
prolog.assertz('index("amigdalitis","amigdalas inflamadas")')
prolog.assertz('index("amigdalitis","dolor al tragar")')
prolog.assertz('index("amigdalitis","dolor de cabeza")')
prolog.assertz('index("amigdalitis","dolor de garganta")')
prolog.assertz('index("amigdalitis","fiebre")')
prolog.assertz('index("aneurisma aortico abdominal","dolor abdominal")')
prolog.assertz('index("aneurisma aortico abdominal","dolor de espalda")')
prolog.assertz('index("aneurisma aortico abdominal","un pulso cerca del ombligo")')
prolog.assertz('index("aneurisma de la aorta toracica","dolor de espalda")')
prolog.assertz('index("aneurisma de la aorta toracica","dolor en el pecho")')
prolog.assertz('index("aneurisma de la aorta toracica","falta de aire")')
prolog.assertz('index("aneurisma de la aorta toracica","ronquera")')
prolog.assertz('index("aneurisma de la aorta toracica","tos")')
prolog.assertz('index("angina de pecho","dolor en el cuello")')
prolog.assertz('index("angina de pecho","dolor en el pecho")')
prolog.assertz('index("angina de pecho","dolor en la espalda")')
prolog.assertz('index("angina de pecho","dolor en la mandibula")')
prolog.assertz('index("angina de pecho","dolor en los brazos")')
prolog.assertz('index("angina de pecho","dolor en los hombros")')
prolog.assertz('index("angina de pecho","dolor o molestia en el pecho")')
prolog.assertz('index("angina de pecho","falta de aire")')
prolog.assertz('index("angina de pecho","fatiga")')
prolog.assertz('index("angina de pecho","mareos")')
prolog.assertz('index("angina de pecho","nauseas")')
prolog.assertz('index("angina de pecho","sudoracion")')
prolog.assertz('index("arritmia cardiaca","aleteo en el pecho")')
prolog.assertz('index("arritmia cardiaca","ansiedad")')
prolog.assertz('index("arritmia cardiaca","dolor en el pecho")')
prolog.assertz('index("arritmia cardiaca","falta de aire")')
prolog.assertz('index("arritmia cardiaca","fatiga")')
prolog.assertz('index("arritmia cardiaca","latidos cardiacos acelerados")')
prolog.assertz('index("arritmia cardiaca","latidos cardiacos lentos")')
prolog.assertz('index("arritmia cardiaca","sudoracion")')
prolog.assertz('index("artritis reumatoide","articulaciones sensibles a la palpacion, calientes e hinchadas")')
prolog.assertz('index("artritis reumatoide","cansancio")')
prolog.assertz('index("artritis reumatoide","fiebre")')
prolog.assertz('index("artritis reumatoide","perdida del apetito")')
prolog.assertz('index("artritis reumatoide","rigidez")')
prolog.assertz('index("bronquitis","dolor en el pecho")')
prolog.assertz('index("bronquitis","escalofrios")')
prolog.assertz('index("bronquitis","fiebre")')
prolog.assertz('index("bronquitis","mucosidad")')
prolog.assertz('index("bronquitis","tos")')
prolog.assertz('index("cancer de pulmon","adelgazamiento")')
prolog.assertz('index("cancer de pulmon","dificultad para respirar")')
prolog.assertz('index("cancer de pulmon","dolor de cabeza")')
prolog.assertz('index("cancer de pulmon","dolor en el pecho")')
prolog.assertz('index("cancer de pulmon","dolor en los huesos.")')
prolog.assertz('index("cancer de pulmon","tos")')
prolog.assertz('index("candidosis oral","agrietamiento y enrojecimiento en las comisuras de la boca")')
prolog.assertz('index("candidosis oral","ardor de boca")')
prolog.assertz('index("candidosis oral","dificultad para comer o tragar")')
prolog.assertz('index("candidosis oral","enrojecimiento boca")')
prolog.assertz('index("candidosis oral","enrojecimiento, irritacion y dolor debajo de las dentaduras")')
prolog.assertz('index("candidosis oral","inflamacion en la boca")')
prolog.assertz('index("candidosis oral","lesiones blancas cremosas en la boca")')
prolog.assertz('index("candidosis oral","perdida del gusto")')
prolog.assertz('index("candidosis oral","sangrado leve")')
prolog.assertz('index("candidosis oral","sensacion algodonosa en la boca")')
prolog.assertz('index("candidosis vaginal","dolores vaginales")')
prolog.assertz('index("candidosis vaginal","inflamacion de la vulva")')
prolog.assertz('index("candidosis vaginal","picazon e irritacion de la vagina y la vulva")')
prolog.assertz('index("candidosis vaginal","sarpullido vaginal")')
prolog.assertz('index("candidosis vaginal","secrecion vaginal acuosa")')
prolog.assertz('index("candidosis vaginal","secrecion vaginal espesa, blanca y sin olor")')
prolog.assertz('index("candidosis vaginal","sensacion de ardor, especialmente durante las relaciones sexuales o al orinar")')
prolog.assertz('index("celiaquia","diarrea")')
prolog.assertz('index("celiaquia","dolor abdominal")')
prolog.assertz('index("celiaquia","estreÃ±imiento")')
prolog.assertz('index("celiaquia","fatiga")')
prolog.assertz('index("celiaquia","gases")')
prolog.assertz('index("celiaquia","hinchazon")')
prolog.assertz('index("celiaquia","nauseas")')
prolog.assertz('index("celiaquia","perdida de peso")')
prolog.assertz('index("celiaquia","vomitos")')
prolog.assertz('index("colitis ulserosa","adelgazamiento")')
prolog.assertz('index("colitis ulserosa","diarrea con sangre o pus")')
prolog.assertz('index("colitis ulserosa","dolor en el recto")')
prolog.assertz('index("colitis ulserosa","dolor y colicos abdominales")')
prolog.assertz('index("colitis ulserosa","fatiga")')
prolog.assertz('index("colitis ulserosa","fiebre")')
prolog.assertz('index("colitis ulserosa","incapacidad para defecar a pesar de la urgencia")')
prolog.assertz('index("colitis ulserosa","necesidad urgente de defecar")')
prolog.assertz('index("colitis ulserosa","problemas de crecimiento en niÃ±os")')
prolog.assertz('index("colitis ulserosa","sangrado rectal")')
prolog.assertz('index("covid-19","cansancio")')
prolog.assertz('index("covid-19","diarrea")')
prolog.assertz('index("covid-19","dificultad para respirar")')
prolog.assertz('index("covid-19","dolor de cabeza")')
prolog.assertz('index("covid-19","dolor de garganta")')
prolog.assertz('index("covid-19","fiebre")')
prolog.assertz('index("covid-19","goteo de la nariz")')
prolog.assertz('index("covid-19","tos")')
prolog.assertz('index("covid-19","vomitos")')
prolog.assertz('index("dermatitis atopica","manchas de color rojo a marron grisaceo")')
prolog.assertz('index("dermatitis atopica","picazon")')
prolog.assertz('index("dermatitis atopica","piel en carne viva, sensible e inflamada por rascarse")')
prolog.assertz('index("dermatitis atopica","piel engrosada, agrietada, escamosa")')
prolog.assertz('index("dermatitis atopica","piel seca")')
prolog.assertz('index("dermatitis atopica","pequeÃ±os bultos, que pueden perder liquido y cubrirse con una costra al rascarse")')
prolog.assertz('index("difteria","dificultad para respirar")')
prolog.assertz('index("difteria","fiebre")')
prolog.assertz('index("difteria","ronquedad")')
prolog.assertz('index("difteria","tos")')
prolog.assertz('index("enfermedad de addison","ansias de consumir sal")')
prolog.assertz('index("enfermedad de addison","bajo nivel de azucar en la sangre")')
prolog.assertz('index("enfermedad de addison","caida del vello corporal o disfuncion sexual en las mujeres")')
prolog.assertz('index("enfermedad de addison","depresion u otros sintomas conductuales")')
prolog.assertz('index("enfermedad de addison","desmayo")')
prolog.assertz('index("enfermedad de addison","diarrea")')
prolog.assertz('index("enfermedad de addison","dolor abdominal")')
prolog.assertz('index("enfermedad de addison","dolor articular")')
prolog.assertz('index("enfermedad de addison","dolor muscular")')
prolog.assertz('index("enfermedad de addison","fatiga extrema")')
prolog.assertz('index("enfermedad de addison","irritabilidad")')
prolog.assertz('index("enfermedad de addison","nauseas")')
prolog.assertz('index("enfermedad de addison","oscurecimiento de la piel")')
prolog.assertz('index("enfermedad de addison","perdida de peso")')
prolog.assertz('index("enfermedad de addison","perdida del apetito")')
prolog.assertz('index("enfermedad de addison","presion arterial baja")')
prolog.assertz('index("enfermedad de addison","vomitos")')
prolog.assertz('index("enfisema pulmonar","coloracion azul en uÃ±as y labios")')
prolog.assertz('index("enfisema pulmonar","dificultad para respirar")')
prolog.assertz('index("faringitis","dolor en el pecho")')
prolog.assertz('index("faringitis","fatiga")')
prolog.assertz('index("faringitis","fiebre")')
prolog.assertz('index("faringitis","soplo cardiaco")')
prolog.assertz('index("foliculitis","ampollas")')
prolog.assertz('index("foliculitis","bultos rojos o espinillas cabeciblancas que se forman alrededor de los foliculos pilosos")')
prolog.assertz('index("foliculitis","picazon o ardor en la piel")')
prolog.assertz('index("foliculitis","sensibilidad en la piel")')
prolog.assertz('index("foliculitis","un gran bulto o protuberancia hinchados")')
prolog.assertz('index("gonorrea","aumento del flujo vaginal")')
prolog.assertz('index("gonorrea","dolor abdominal")')
prolog.assertz('index("gonorrea","dolor al orinar")')
prolog.assertz('index("gonorrea","dolor al orinar")')
prolog.assertz('index("gonorrea","dolor o hinchazon en un testiculo")')
prolog.assertz('index("gonorrea","sangrado vaginal")')
prolog.assertz('index("gonorrea","secrecion similar al pus de la punta del pene")')
prolog.assertz('index("herpes genital","ampollas")')
prolog.assertz('index("herpes genital","costras en la piel")')
prolog.assertz('index("herpes genital","dolor")')
prolog.assertz('index("herpes genital","picazon")')
prolog.assertz('index("herpes genital","protuberancias rojas pequeÃ±as")')
prolog.assertz('index("herpes genital","ulceras")')
prolog.assertz('index("herpes labial","ampollas")')
prolog.assertz('index("herpes labial","costras")')
prolog.assertz('index("herpes labial","dolor de cabeza")')
prolog.assertz('index("herpes labial","dolor de garganta")')
prolog.assertz('index("herpes labial","dolor muscular")')
prolog.assertz('index("herpes labial","encias erosionadas")')
prolog.assertz('index("herpes labial","fiebre")')
prolog.assertz('index("herpes labial","ganglios linfaticos inflamados")')
prolog.assertz('index("herpes labial","hormigueo")')
prolog.assertz('index("herpes labial","picazon")')
prolog.assertz('index("herpes labial","supuracion")')
prolog.assertz('index("hipertension pulmonar","coloracion azul en uÃ±as y labios")')
prolog.assertz('index("hipertension pulmonar","desmayos")')
prolog.assertz('index("hipertension pulmonar","dificultad para respirar")')
prolog.assertz('index("hipertension pulmonar","dolor en el pecho")')
prolog.assertz('index("hipertension pulmonar","fatiga")')
prolog.assertz('index("hipertension pulmonar","hinchazon en los tobillos y las piernas")')
prolog.assertz('index("hipertension pulmonar","mareos")')
prolog.assertz('index("hipertension pulmonar","pulso acelerado")')
prolog.assertz('index("histoplasmosis","dolor de cabeza")')
prolog.assertz('index("histoplasmosis","dolor muscular")')
prolog.assertz('index("histoplasmosis","escalofrios")')
prolog.assertz('index("histoplasmosis","fatiga")')
prolog.assertz('index("histoplasmosis","fiebre")')
prolog.assertz('index("histoplasmosis","molestia en el pecho")')
prolog.assertz('index("histoplasmosis","tos seca")')
prolog.assertz('index("insuficiencia cardiaca","aumento de peso muy rapido por retencion de liquido")')
prolog.assertz('index("insuficiencia cardiaca","dificultad para concentrarse o menor estado de alerta")')
prolog.assertz('index("insuficiencia cardiaca","dolor en el pecho")')
prolog.assertz('index("insuficiencia cardiaca","falta de aire")')
prolog.assertz('index("insuficiencia cardiaca","falta de aire")')
prolog.assertz('index("insuficiencia cardiaca","falta de apetito")')
prolog.assertz('index("insuficiencia cardiaca","fatiga y debilidad")')
prolog.assertz('index("insuficiencia cardiaca","hinchazon del abdomen")')
prolog.assertz('index("insuficiencia cardiaca","hinchazon en los tobillos y las piernas")')
prolog.assertz('index("insuficiencia cardiaca","latidos del corazon acelerados")')
prolog.assertz('index("insuficiencia cardiaca","mayor necesidad de orinar por la noche")')
prolog.assertz('index("insuficiencia cardiaca","menor capacidad para hacer ejercicio")')
prolog.assertz('index("insuficiencia cardiaca","nauseas")')
prolog.assertz('index("insuficiencia cardiaca","sibilancia constantes con flema blanca o rosa manchada de sangre")')
prolog.assertz('index("insuficiencia cardiaca","tos")')
prolog.assertz('index("lupus","dedos de los pies y de las manos que se vuelven blancos o azules cuando se exponen al frio o durante situaciones de estres")')       
prolog.assertz('index("lupus","desorientacion")')
prolog.assertz('index("lupus","dolor articular")')
prolog.assertz('index("lupus","dolor de cabeza")')
prolog.assertz('index("lupus","dolor en el pecho")')
prolog.assertz('index("lupus","erupcion")')
prolog.assertz('index("lupus","falta de aire")')
prolog.assertz('index("lupus","fatiga")')
prolog.assertz('index("lupus","fiebre")')
prolog.assertz('index("lupus","fotosensibilidad")')
prolog.assertz('index("lupus","ojos secos")')
prolog.assertz('index("lupus","perdida de memoria")')
prolog.assertz('index("malformacion arteriovenosa","dolor de cabeza")')
prolog.assertz('index("malformacion arteriovenosa","nauseas")')
prolog.assertz('index("malformacion arteriovenosa","perdida del conocimiento")')
prolog.assertz('index("malformacion arteriovenosa","perdida progresiva de la funcion neurologica")')
prolog.assertz('index("malformacion arteriovenosa","sangrado")')
prolog.assertz('index("malformacion arteriovenosa","convulsiones")')
prolog.assertz('index("malformacion arteriovenosa","vomitos")')
prolog.assertz('index("narcolepsia","alucinaciones")')
prolog.assertz('index("narcolepsia","cambios en el ciclo de sueÃ±o con movimiento rapido de ojos (rem)")')
prolog.assertz('index("narcolepsia","paralisis del sueÃ±o")')
prolog.assertz('index("narcolepsia","perdida repentina del tono muscular")')
prolog.assertz('index("narcolepsia","somnolencia excesiva durante el dia")')
prolog.assertz('index("neumonia","dolor en el pecho")')
prolog.assertz('index("neumonia","fatiga")')
prolog.assertz('index("neumonia","fiebre")')
prolog.assertz('index("neumonia","mucosidad")')
prolog.assertz('index("neumonia","tos")')
prolog.assertz('index("neumonia","vomitos")')
prolog.assertz('index("psoriasis","ardor")')
prolog.assertz('index("psoriasis","articulaciones inflamadas y rigidas")')
prolog.assertz('index("psoriasis","dolor")')
prolog.assertz('index("psoriasis","manchas rojas en la piel cubiertas con escamas gruesas y plateadas")')
prolog.assertz('index("psoriasis","pequeÃ±os puntos escamados")')
prolog.assertz('index("psoriasis","picazon")')
prolog.assertz('index("psoriasis","piel seca ")')
prolog.assertz('index("psoriasis","uÃ±as engrosadas, picadas o acanaladas")')
prolog.assertz('index("rinitis","congestion nasal")')
prolog.assertz('index("rinitis","estornudos")')
prolog.assertz('index("rinitis","mucosidad")')
prolog.assertz('index("rinitis","tos")')
prolog.assertz('index("rinosinusitis","dolor de cabeza")')
prolog.assertz('index("rinosinusitis","dolor de garganta")')
prolog.assertz('index("rinosinusitis","mucosidad")')
prolog.assertz('index("rinosinusitis","perdida de olfato")')
prolog.assertz('index("rinosinusitis","tos")')
prolog.assertz('index("sida","diarrea")')
prolog.assertz('index("sida","dolor articular")')
prolog.assertz('index("sida","dolor de cabeza")')
prolog.assertz('index("sida","dolor de garganta")')
prolog.assertz('index("sida","dolor muscular")')
prolog.assertz('index("sida","erupcion")')
prolog.assertz('index("sida","fiebre")')
prolog.assertz('index("sida","ganglios linfaticos inflamados")')
prolog.assertz('index("sida","llagas dolorosas en la boca")')
prolog.assertz('index("sida","perdida de peso")')
prolog.assertz('index("sida","sudoracion nocturna")')
prolog.assertz('index("sida","tos")')
prolog.assertz('index("sindrome coronario agudo","aturdimiento, mareos o desmayos")')
prolog.assertz('index("sindrome coronario agudo","dificultad para respirar")')
prolog.assertz('index("sindrome coronario agudo","dolor que se extiende desde el pecho hasta los hombros, los brazos, la parte superior del abdomen, la espalda, el cuello o la mandibula")')
prolog.assertz('index("sindrome coronario agudo","dolor toracico")')
prolog.assertz('index("sindrome coronario agudo","fatiga inusual o inexplicable")')
prolog.assertz('index("sindrome coronario agudo","indigestion")')
prolog.assertz('index("sindrome coronario agudo","nauseas")')
prolog.assertz('index("sindrome coronario agudo","sensacion de inquietud o aprension")')
prolog.assertz('index("sindrome coronario agudo","sudoracion")')
prolog.assertz('index("sindrome coronario agudo","vomitos")')
prolog.assertz('index("soplos cardiacos","agrandamiento de las venas del cuello")')
prolog.assertz('index("soplos cardiacos","agrandamiento del higado")')
prolog.assertz('index("soplos cardiacos","aumento de peso repentino")')
prolog.assertz('index("soplos cardiacos","coloracion azul en uÃ±as y labios.")')
prolog.assertz('index("soplos cardiacos","dolor en el pecho")')
prolog.assertz('index("soplos cardiacos","falta de aire")')
prolog.assertz('index("soplos cardiacos","mareos")')
prolog.assertz('index("soplos cardiacos","sudoracion")')
prolog.assertz('index("soplos cardiacos","tos cronica")')
prolog.assertz('index("soplos cardiacos","desmayo")')
prolog.assertz('index("tosferina","congestion nasal")')
prolog.assertz('index("tosferina","fiebre")')
prolog.assertz('index("tosferina","mucosidad")')
prolog.assertz('index("tosferina","ojos llorosos")')
prolog.assertz('index("tosferina","tos")')
prolog.assertz('index("urticaria","ronchas grandes")')
prolog.assertz('index("urticaria","ronchas pequeÃ±as")')
prolog.assertz('index("urticaria","ronchas redondas, ovaladas o en forma de gusano")')
prolog.assertz('index("urticaria","ronchas rojizas")')
prolog.assertz('index("urticaria","una comezon de leve a intensa")')
prolog.assertz('index("urticaria cronica","hinchazon dolorosa de los labios, los parpados, y el interior de la garganta")')
prolog.assertz('index("urticaria cronica","intensifican sintomas con desencadenantes como calor, ejercicio y estres")')
prolog.assertz('index("urticaria cronica","picazon, que puede ser intensa")')
prolog.assertz('index("urticaria cronica","ronchas")')
prolog.assertz('index("urticaria cronica","ronchas rojas o del color de la piel")')
prolog.assertz('index("urticaria cronica","sintomas continuan y reaparecen con frecuencia")')
prolog.assertz('index("urticaria por frio","hinchazon de las manos al agarrar objetos frios")')
prolog.assertz('index("urticaria por frio","hinchazon de los labios al consumir alimentos y bebidas frios")')
prolog.assertz('index("urticaria por frio","ronchas rojizas")')
prolog.assertz('index("urticaria por frio","un empeoramiento de la reaccion a medida que la piel se calienta")')

# Query Example
#testQuery = list(prolog.query('index("urticaria por frio","un empeoramiensto de la reaccion a medida que la piel se calienta")'))
#if testQuery == []:
#    print(False)
#else:
#    print(True)
